### ISSUE TITLE
spice.so image not found

### ISSUE THREAD

**Issue by dstansby** [AndrewAnnex/SpiceyPy#243]
I've just tried to install SpiceyPy using the instructions, but trying to import it errors:

```python
import spiceypy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/spiceypy/__init__.py", line 25, in <module>
    from .spiceypy import *
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/spiceypy/spiceypy.py", line 27, in <module>
    from .utils.libspicehelper import libspice
  File "/Users/dstansby/miniconda3/lib/python3.6/site-packages/spiceypy/utils/libspicehelper.py", line 34, in <module>
    libspice = CDLL(sitePath)
  File "/Users/dstansby/miniconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/dstansby/miniconda3/lib/python3.6/site-packages/spiceypy/utils/spice.so, 6): image not found
```

**Comment by dstansby** [comment]
Woops, duplicate of #240

**Comment by AndrewAnnex** [comment]
There is currently an issue with setup tools that will cause a command to be skipped during install that I haven't got around to fixing, see #240 #242 for the fix. This assumes you installed using pip, as you are using anaconda if you ran the conda install command I think you would have not seen the issue.
