### ISSUE TITLE
Broken pip package version 2.1.0

### ISSUE THREAD

**Issue by ChristopherRabotin** [AndrewAnnex/SpiceyPy#256]
The package on PyPi is broken as it is mission `spice.so`. Here's an example where I create a new virtual environment, and simply install spiceypy 2.1.0.

# Using Python 3
```
> virtualenv .venv2
Using base prefix '/usr'
New python executable in /home/chris/Workspace/mypath/.venv2/bin/python3
Also creating executable in /home/chris/Workspace/mypath/.venv2/bin/python
Installing setuptools, pip, wheel...done.
chris@linux-fkyc:~/Workspace/mypath> source .venv2/bin/activate
(.venv2) chris@linux-fkyc:~/Workspace/mypath> pip install spiceypy
Collecting spiceypy
  Downloading https://files.pythonhosted.org/packages/dc/95/fb8d53379dc860f4a5add14027c378383b2ae6f0394e24b681d352ea06d1/spiceypy-2.1.0.tar.gz (113kB)
    100% |████████████████████████████████| 122kB 3.0MB/s 
Collecting numpy>=1.12.0 (from spiceypy)
  Downloading https://files.pythonhosted.org/packages/7e/09/c5a2822aa55a9cf89c6398780bbcaa1fede0650cdccd55bc89a8548c0d7a/numpy-1.14.2-cp34-cp34m-manylinux1_x86_64.whl (12.1MB)
    100% |████████████████████████████████| 12.1MB 794kB/s 
Collecting six>=1.9.0 (from spiceypy)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting certifi>=2017.1.23 (from spiceypy)
  Downloading https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl (150kB)
    100% |████████████████████████████████| 153kB 3.9MB/s 
Building wheels for collected packages: spiceypy
  Running setup.py bdist_wheel for spiceypy ... done
  Stored in directory: /home/chris/.cache/pip/wheels/77/ef/23/d122a86daa48dfd8607485f156c513570c6d992cc502164fd8
Successfully built spiceypy
Installing collected packages: numpy, six, certifi, spiceypy
Successfully installed certifi-2018.4.16 numpy-1.14.2 six-1.11.0 spiceypy-2.1.0
(.venv2) chris@linux-fkyc:~/Workspace/mypath> python
Python 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spiceypy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/Workspace/mypath/.venv2/lib/python3.4/site-packages/spiceypy/__init__.py", line 25, in <module>
    from .spiceypy import *
  File "/home/chris/Workspace/mypath/.venv2/lib/python3.4/site-packages/spiceypy/spiceypy.py", line 27, in <module>
    from .utils.libspicehelper import libspice
  File "/home/chris/Workspace/mypath/.venv2/lib/python3.4/site-packages/spiceypy/utils/libspicehelper.py", line 34, in <module>
    libspice = CDLL(sitePath)
  File "/usr/lib64/python3.4/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/chris/Workspace/mypath/.venv2/lib/python3.4/site-packages/spiceypy/utils/spice.so: cannot open shared object file: No such file or directory
>>> 
```

# Using Python 2

```
> virtualenv .venv2 -p `which python2`
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/chris/Workspace/mypath/.venv2/bin/python2
Also creating executable in /home/chris/Workspace/mypath/.venv2/bin/python
Installing setuptools, pip, wheel...done.
chris@linux-fkyc:~/Workspace/mypath> source .venv2/bin/activate
(.venv2) chris@linux-fkyc:~/Workspace/mypath> pip install spiceypy
Collecting spiceypy
Collecting numpy>=1.12.0 (from spiceypy)
  Downloading https://files.pythonhosted.org/packages/76/4d/418dda252cf92bad00ab82d6b2a856e7843b47a5c2f084aed34b14b67d64/numpy-1.14.2-cp27-cp27mu-manylinux1_x86_64.whl (12.1MB)
    100% |████████████████████████████████| 12.1MB 1.5MB/s 
Collecting pytest>=2.9.0 (from spiceypy)
  Downloading https://files.pythonhosted.org/packages/ed/96/271c93f75212c06e2a7ec3e2fa8a9c90acee0a4838dc05bf379ea09aae31/pytest-3.5.0-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 5.9MB/s 
Collecting six>=1.9.0 (from spiceypy)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest>=2.9.0->spiceypy)
  Downloading https://files.pythonhosted.org/packages/67/a5/f77982214dd4c8fd104b066f249adea2c49e25e8703d284382eb5e9ab35a/py-1.5.3-py2.py3-none-any.whl (84kB)
    100% |████████████████████████████████| 92kB 9.8MB/s 
Collecting pluggy<0.7,>=0.5 (from pytest>=2.9.0->spiceypy)
  Downloading https://files.pythonhosted.org/packages/82/05/43e3947125a2137cba4746135c75934ceed1863f27e050fc560052104a71/pluggy-0.6.0-py2-none-any.whl
Collecting funcsigs; python_version < "3.0" (from pytest>=2.9.0->spiceypy)
  Downloading https://files.pythonhosted.org/packages/69/cb/f5be453359271714c01b9bd06126eaf2e368f1fddfff30818754b5ac2328/funcsigs-1.0.2-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest>=2.9.0->spiceypy)
  Downloading https://files.pythonhosted.org/packages/4a/88/c28e2a2da8f3dc3a391d9c97ad949f2ea0c05198222e7e6af176e5bf9b26/more_itertools-4.1.0-py2-none-any.whl (47kB)
    100% |████████████████████████████████| 51kB 7.1MB/s 
Collecting attrs>=17.4.0 (from pytest>=2.9.0->spiceypy)
  Downloading https://files.pythonhosted.org/packages/b5/60/4e178c1e790fd60f1229a9b3cb2f8bc2f4cc6ff2c8838054c142c70b5adc/attrs-17.4.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./.venv2/lib/python2.7/site-packages (from pytest>=2.9.0->spiceypy) (39.0.1)
Installing collected packages: numpy, py, six, pluggy, funcsigs, more-itertools, attrs, pytest, spiceypy
Successfully installed attrs-17.4.0 funcsigs-1.0.2 more-itertools-4.1.0 numpy-1.14.2 pluggy-0.6.0 py-1.5.3 pytest-3.5.0 six-1.11.0 spiceypy-2.1.0
(.venv2) chris@linux-fkyc:~/Workspace/mypath> python
Python 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import spiceypy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/Workspace/mypath/.venv2/lib/python2.7/site-packages/spiceypy/__init__.py", line 25, in <module>
    from .spiceypy import *
  File "/home/chris/Workspace/mypath/.venv2/lib/python2.7/site-packages/spiceypy/spiceypy.py", line 27, in <module>
    from .utils.libspicehelper import libspice
  File "/home/chris/Workspace/mypath/.venv2/lib/python2.7/site-packages/spiceypy/utils/libspicehelper.py", line 34, in <module>
    libspice = CDLL(sitePath)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/chris/Workspace/mypath/.venv2/lib/python2.7/site-packages/spiceypy/utils/spice.so: cannot open shared object file: No such file or directory
>>> 
```

I won't hide that this is slightly frustrating since version 2.0.0 required a manual install of `six` before attempting to install spiceypy ;-)

**Comment by AndrewAnnex** [comment]
yeah this is something I am actively working on in #246 #255 but the issue is due to pip as far as I can tell at the moment. 
the fix is to run `pip install spiceypy --no-cache-dir` 
 ee #245 and or #240
